name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      env:
        ACCUWEATHER_APIKEY: ${{ secrets.ACCUWEATHER_APIKEY }}
        BINGMAPS_APIKEY: ${{ secrets.BINGMAPS_APIKEY }}
        OPENWEATHER_APIKEY: ${{ secrets.OPENWEATHER_APIKEY }}
      run: dotnet test --no-restore --verbosity normal
